export function dropzone(on_drop) {
  let generated_dropzone = `
  <style>
      #drop-zone {
      width: 100%;
      max-width: 400px;
      height: 200px;
      padding: 25px;
      border: 2px dashed #ccc;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      cursor: pointer;
    }

    /* Class to be added via JavaScript when dragging over */
    #drop-zone.drag-over {
      border-color: #000;
      background-color: #eee;
    }
  </style>
	<div id="drop-zone">
    <p>Upload your Roblox Rig that has been generated by avatarBoom.</p>
    <p>Drag & drop the files in the files here:</p>
      <!-- Hidden input to allow clicking to select files -->
      <input type="file" id="file-input" multiple hidden>
  </div>
`
  let dropZone = document.getElementById('drop-zone');
  dropZone.addEventListener('drop', on_drop);
  return generated_dropzone
}
